FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5173

# Se especifica --host para que Vite escuche peticiones fuera del contenedor
CMD ["npm", "run", "dev", "--", "--host"]